apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimo-springboot-app
  labels:
    app: kimo-springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kimo-springboot-app

  template:
    metadata:
      labels:
        app: kimo-springboot-app
  
    spec:
      containers:
      - name: kimo-springboot-app

        image: gcr.io/sandbox-io-289003/kimo-app:master.1
        ports:
        - containerPort: 8080
